backup/app/routes/home.py
from flask import Blueprint, render_template

bp = Blueprint(
    'home', __name__,
    static_folder='../static',
    template_folder='../templates'
)


@bp.route('/')
def index():
    return render_template('home.html')

# from flask import Flask, render_template

# app = Flask(__name__)


# @app.route('/')
# def main_page():
#     return render_template('home.html')

# if __name__ == '__main__':
#     app.run(debug=True)

backup/app/routes/payment.py
from flask import Blueprint, render_template

bp = Blueprint(
    'payment', __name__,
    static_folder='../static',
    template_folder='../templates'
)


@bp.route('/donate')
def donate():
    return render_template('payment.html')

backup/app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Site{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>

<body>
    <nav>
        <a href="{{ url_for('home.index') }}">Home</a>
        <a href="{{ url_for('payment.donate') }}">Donation</a>
    </nav>
    <div>
        {% block content %}{% endblock %}
    </div>
</body>

</html>

backup/app/templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

<!DOCTYPE html>
<html lang="en">

<head>
    <style>
        body {
            background-color: skyblue;
        }
    </style>
</head>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <style>
        .container {
            display: flex;
            flex-direction: column;
            align-items: center;
            text-align: center;
        }

        .row {
            display: flex;
            justify-content: center;
            margin: 20px 0;
        }

        .text-box_0 {
            width: 700px;
            margin: 0 20px;
        }

        .text-box {
            width: 20px;
            margin: 0 30px;
            writing-mode: vertical-rl;
            text-orientation: middle;
        }

        .image {
            max-width: 30%;
            height: auto;
        }
    </style>
</head>

<body>
    {% block content %}
    <div class="container">
        <div class="row">
            <div class="text-box_0" style="font-size: 48px;">南无药师琉璃光如来</div>
        </div>
        <div class="row">
            <div class="text-box" style="font-size: 36px;">无上士</div>
            <img src="{{ url_for('static', filename='images/main_pic.jpeg') }}" alt="Main Image" class="image">
            <div class="text-box" style="font-size: 36px; margin-left: 50px;">天人师</div>
        </div>
        <div class="row">
            <div class="text-box" style="font-size: 36px;">佛</div>
        </div>
    </div>
    {% endblock %}
</body>

</html>

backup/app/templates/payment.html
<!DOCTYPE html>
<html lang="en">

<head>
    <style>
        body {
            background-color: skyblue;
        }
    </style>
</head>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <style>
        .container {
            display: flex;
            flex-direction: column;
            align-items: center;
            text-align: center;
        }

        .row {
            display: flex;
            justify-content: center;
            margin: 20px 0;
        }

        .text-box_0 {
            width: 700px;
            margin: 0 20px;
        }

        .text-box {
            width: 20px;
            margin: 0 30px;
            writing-mode: vertical-rl;
            text-orientation: middle;
        }

        .image {
            max-width: 30%;
            height: auto;
        }
    </style>
</head>

<body>
    {% block content %}
    <div class="container">
        <div class="row">
            <div class="text-box" style="font-size: 48px;">thank you</div>
        </div>
        <div class="row">
            <img src="{{ url_for('static', filename='images/qr.jpeg') }}" alt="Main Image" class="image">
        </div>
    </div>
    {% endblock %}
</body>

</html>